"""Constantes pour l'intégration RFXCOM."""

DOMAIN = "rfxcom"
DEFAULT_PORT = "/dev/ttyUSB0"
DEFAULT_BAUDRATE = 38400
DEFAULT_HOST = "localhost"
DEFAULT_NETWORK_PORT = 10001

# Types de connexion
CONNECTION_TYPE_USB = "usb"
CONNECTION_TYPE_NETWORK = "network"

# Protocoles supportés - Lighting1 (0x10)
PROTOCOL_X10 = "X10"
PROTOCOL_ARC = "ARC"
PROTOCOL_ABICOD = "ABICOD"
PROTOCOL_WAVEMAN = "WAVEMAN"
PROTOCOL_EMW100 = "EMW100"
PROTOCOL_IMPULS = "IMPULS"
PROTOCOL_RISINGSUN = "RISINGSUN"
PROTOCOL_PHILIPS = "PHILIPS"
PROTOCOL_ENERGENIE = "ENERGENIE"
PROTOCOL_ENERGENIE_5 = "ENERGENIE_5"
PROTOCOL_COCOSTICK = "COCOSTICK"

# Protocoles supportés - Lighting2 (0x11)
PROTOCOL_AC = "AC"
PROTOCOL_HOMEEASY_EU = "HOMEEASY_EU"
PROTOCOL_ANSLUT = "ANSLUT"
PROTOCOL_KAMBROOK = "KAMBROOK"

# Protocoles supportés - Lighting3 (0x12)
PROTOCOL_IKEA_KOPPLA = "IKEA_KOPPLA"

# Protocoles supportés - Lighting4 (0x13)
PROTOCOL_PT2262 = "PT2262"

# Protocoles supportés - Lighting5 (0x14)
PROTOCOL_LIGHTWAVERF = "LIGHTWAVERF"
PROTOCOL_EMW100_GDO = "EMW100_GDO"
PROTOCOL_BBSB = "BBSB"
PROTOCOL_RSL = "RSL"
PROTOCOL_LIVOLO = "LIVOLO"
PROTOCOL_TRC02 = "TRC02"
PROTOCOL_AOKE = "AOKE"
PROTOCOL_RGB_TRC02 = "RGB_TRC02"

# Protocoles supportés - Lighting6 (0x15)
PROTOCOL_BLYSS = "BLYSS"

# Protocoles supportés - Autres
PROTOCOL_TEMP_HUM = "TEMP_HUM"

# Liste de tous les protocoles pour les interrupteurs/prises
PROTOCOLS_SWITCH = [
    # Lighting1
    PROTOCOL_X10,
    PROTOCOL_ARC,
    PROTOCOL_ABICOD,
    PROTOCOL_WAVEMAN,
    PROTOCOL_EMW100,
    PROTOCOL_IMPULS,
    PROTOCOL_RISINGSUN,
    PROTOCOL_PHILIPS,
    PROTOCOL_ENERGENIE,
    PROTOCOL_ENERGENIE_5,
    PROTOCOL_COCOSTICK,
    # Lighting2
    PROTOCOL_AC,
    PROTOCOL_HOMEEASY_EU,
    PROTOCOL_ANSLUT,
    PROTOCOL_KAMBROOK,
    # Lighting3
    PROTOCOL_IKEA_KOPPLA,
    # Lighting4
    PROTOCOL_PT2262,
    # Lighting5
    PROTOCOL_LIGHTWAVERF,
    PROTOCOL_EMW100_GDO,
    PROTOCOL_BBSB,
    PROTOCOL_RSL,
    PROTOCOL_LIVOLO,
    PROTOCOL_TRC02,
    PROTOCOL_AOKE,
    PROTOCOL_RGB_TRC02,
    # Lighting6
    PROTOCOL_BLYSS,
]

# Types d'appareils
DEVICE_TYPE_SWITCH = "switch"
DEVICE_TYPE_LIGHT = "light"
DEVICE_TYPE_SENSOR = "sensor"

# Commandes
CMD_ON = "ON"
CMD_OFF = "OFF"

# Configuration
CONF_PORT = "port"
CONF_BAUDRATE = "baudrate"
CONF_HOST = "host"
CONF_NETWORK_PORT = "network_port"
CONF_CONNECTION_TYPE = "connection_type"
CONF_PROTOCOL = "protocol"
CONF_UNIT_CODE = "unit_code"
CONF_HOUSE_CODE = "house_code"
CONF_DEVICE_ID = "device_id"
CONF_PAIRING_MODE = "pairing_mode"
CONF_ENABLED_PROTOCOLS = "enabled_protocols"
PROTOCOL_AUTO = "auto"

# RFXCOM Packet Types
PACKET_TYPE_LIGHTING1 = 0x10
PACKET_TYPE_LIGHTING2 = 0x11
PACKET_TYPE_LIGHTING3 = 0x12
PACKET_TYPE_LIGHTING4 = 0x13
PACKET_TYPE_LIGHTING5 = 0x14
PACKET_TYPE_LIGHTING6 = 0x15
PACKET_TYPE_TEMP_HUM = 0x52

# Lighting1 Subtypes (0x10)
SUBTYPE_X10 = 0x00
SUBTYPE_ARC = 0x01
SUBTYPE_ABICOD = 0x02
SUBTYPE_WAVEMAN = 0x03
SUBTYPE_EMW100 = 0x04
SUBTYPE_IMPULS = 0x05
SUBTYPE_RISINGSUN = 0x06
SUBTYPE_PHILIPS = 0x07
SUBTYPE_ENERGENIE = 0x08
SUBTYPE_ENERGENIE_5 = 0x09
SUBTYPE_COCOSTICK = 0x0A

# Lighting2 Subtypes (0x11)
SUBTYPE_AC = 0x00
SUBTYPE_HOMEEASY_EU = 0x01
SUBTYPE_ANSLUT = 0x02
SUBTYPE_KAMBROOK = 0x03

# Lighting5 Subtypes (0x14)
SUBTYPE_LIGHTWAVERF = 0x00
SUBTYPE_EMW100_GDO = 0x01
SUBTYPE_BBSB = 0x02
SUBTYPE_RSL = 0x03
SUBTYPE_LIVOLO = 0x04
SUBTYPE_TRC02 = 0x05
SUBTYPE_AOKE = 0x06
SUBTYPE_RGB_TRC02 = 0x07

# TEMP_HUM Subtypes (0x52)
SUBTYPE_TH13 = 0x0D  # Alecto WS1700 and compatibles

# Mapping protocole -> (packet_type, subtype)
PROTOCOL_TO_PACKET = {
    # Lighting1
    PROTOCOL_X10: (PACKET_TYPE_LIGHTING1, SUBTYPE_X10),
    PROTOCOL_ARC: (PACKET_TYPE_LIGHTING1, SUBTYPE_ARC),
    PROTOCOL_ABICOD: (PACKET_TYPE_LIGHTING1, SUBTYPE_ABICOD),
    PROTOCOL_WAVEMAN: (PACKET_TYPE_LIGHTING1, SUBTYPE_WAVEMAN),
    PROTOCOL_EMW100: (PACKET_TYPE_LIGHTING1, SUBTYPE_EMW100),
    PROTOCOL_IMPULS: (PACKET_TYPE_LIGHTING1, SUBTYPE_IMPULS),
    PROTOCOL_RISINGSUN: (PACKET_TYPE_LIGHTING1, SUBTYPE_RISINGSUN),
    PROTOCOL_PHILIPS: (PACKET_TYPE_LIGHTING1, SUBTYPE_PHILIPS),
    PROTOCOL_ENERGENIE: (PACKET_TYPE_LIGHTING1, SUBTYPE_ENERGENIE),
    PROTOCOL_ENERGENIE_5: (PACKET_TYPE_LIGHTING1, SUBTYPE_ENERGENIE_5),
    PROTOCOL_COCOSTICK: (PACKET_TYPE_LIGHTING1, SUBTYPE_COCOSTICK),
    # Lighting2
    PROTOCOL_AC: (PACKET_TYPE_LIGHTING2, SUBTYPE_AC),
    PROTOCOL_HOMEEASY_EU: (PACKET_TYPE_LIGHTING2, SUBTYPE_HOMEEASY_EU),
    PROTOCOL_ANSLUT: (PACKET_TYPE_LIGHTING2, SUBTYPE_ANSLUT),
    PROTOCOL_KAMBROOK: (PACKET_TYPE_LIGHTING2, SUBTYPE_KAMBROOK),
    # Lighting3
    PROTOCOL_IKEA_KOPPLA: (PACKET_TYPE_LIGHTING3, None),
    # Lighting4
    PROTOCOL_PT2262: (PACKET_TYPE_LIGHTING4, None),
    # Lighting5
    PROTOCOL_LIGHTWAVERF: (PACKET_TYPE_LIGHTING5, SUBTYPE_LIGHTWAVERF),
    PROTOCOL_EMW100_GDO: (PACKET_TYPE_LIGHTING5, SUBTYPE_EMW100_GDO),
    PROTOCOL_BBSB: (PACKET_TYPE_LIGHTING5, SUBTYPE_BBSB),
    PROTOCOL_RSL: (PACKET_TYPE_LIGHTING5, SUBTYPE_RSL),
    PROTOCOL_LIVOLO: (PACKET_TYPE_LIGHTING5, SUBTYPE_LIVOLO),
    PROTOCOL_TRC02: (PACKET_TYPE_LIGHTING5, SUBTYPE_TRC02),
    PROTOCOL_AOKE: (PACKET_TYPE_LIGHTING5, SUBTYPE_AOKE),
    PROTOCOL_RGB_TRC02: (PACKET_TYPE_LIGHTING5, SUBTYPE_RGB_TRC02),
    # Lighting6
    PROTOCOL_BLYSS: (PACKET_TYPE_LIGHTING6, None),
}

# Auto-registry
CONF_AUTO_REGISTRY = "auto_registry"
DEFAULT_AUTO_REGISTRY = False

# Timeouts
PAIRING_TIMEOUT = 30  # secondes

